# Book settings
title: Deep Learning Course
author: Alberto Ezpondaburu
copyright: "2025"
logo: ""

# Execution settings
execute:
  execute_notebooks: "off"

# Parse settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - amsmath

# HTML settings
html:
  baseurl: https://ezponda.github.io/deep-learning-course/
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false
  extra_footer: |
    <div style="margin-top: 10px;">
      By Alberto Ezpondaburu
      <a href="https://www.linkedin.com/in/alberto-ezpondaburu-merino-305394ab/" target="_blank" style="margin-left: 10px; color: inherit;"><i class="fab fa-linkedin fa-lg"></i></a>
      <a href="https://github.com/ezponda" target="_blank" style="margin-left: 8px; color: inherit;"><i class="fab fa-github fa-lg"></i></a>
    </div>

# Repository settings
repository:
  url: https://github.com/ezponda/deep-learning-course
  branch: main
  path_to_book: book

# Launch button settings
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
